//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Stumptown40Model", "FK_Round_BracketId", "Bracket", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Website.Models.Bracket), "Round", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Website.Models.Round), true)]
[assembly: EdmRelationshipAttribute("Stumptown40Model", "FK_Match_NextLosingMatchId", "Match", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Website.Models.Match), "Match1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Website.Models.Match), true)]
[assembly: EdmRelationshipAttribute("Stumptown40Model", "FK_Match_NextWinningMatchId", "Match", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Website.Models.Match), "Match1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Website.Models.Match), true)]
[assembly: EdmRelationshipAttribute("Stumptown40Model", "FK_Match_Racer1Id", "Racer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Website.Models.Racer), "Match", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Website.Models.Match), true)]
[assembly: EdmRelationshipAttribute("Stumptown40Model", "FK_Match_Racer2Id", "Racer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Website.Models.Racer), "Match", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Website.Models.Match), true)]
[assembly: EdmRelationshipAttribute("Stumptown40Model", "FK_Match_RoundId", "Round", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Website.Models.Round), "Match", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Website.Models.Match), true)]
[assembly: EdmRelationshipAttribute("Stumptown40Model", "FK_Match_WinningRacerId", "Racer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Website.Models.Racer), "Match", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Website.Models.Match), true)]

#endregion

namespace Website.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Stumptown40Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Stumptown40Entities object using the connection string found in the 'Stumptown40Entities' section of the application configuration file.
        /// </summary>
        public Stumptown40Entities() : base("name=Stumptown40Entities", "Stumptown40Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Stumptown40Entities object.
        /// </summary>
        public Stumptown40Entities(string connectionString) : base(connectionString, "Stumptown40Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Stumptown40Entities object.
        /// </summary>
        public Stumptown40Entities(EntityConnection connection) : base(connection, "Stumptown40Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bracket> Brackets
        {
            get
            {
                if ((_Brackets == null))
                {
                    _Brackets = base.CreateObjectSet<Bracket>("Brackets");
                }
                return _Brackets;
            }
        }
        private ObjectSet<Bracket> _Brackets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Match> Matches
        {
            get
            {
                if ((_Matches == null))
                {
                    _Matches = base.CreateObjectSet<Match>("Matches");
                }
                return _Matches;
            }
        }
        private ObjectSet<Match> _Matches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Racer> Racers
        {
            get
            {
                if ((_Racers == null))
                {
                    _Racers = base.CreateObjectSet<Racer>("Racers");
                }
                return _Racers;
            }
        }
        private ObjectSet<Racer> _Racers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Round> Rounds
        {
            get
            {
                if ((_Rounds == null))
                {
                    _Rounds = base.CreateObjectSet<Round>("Rounds");
                }
                return _Rounds;
            }
        }
        private ObjectSet<Round> _Rounds;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Brackets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBrackets(Bracket bracket)
        {
            base.AddObject("Brackets", bracket);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Matches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMatches(Match match)
        {
            base.AddObject("Matches", match);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Racers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRacers(Racer racer)
        {
            base.AddObject("Racers", racer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rounds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRounds(Round round)
        {
            base.AddObject("Rounds", round);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stumptown40Model", Name="Bracket")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bracket : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bracket object.
        /// </summary>
        /// <param name="bracketId">Initial value of the BracketId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Bracket CreateBracket(global::System.Int32 bracketId, global::System.String name)
        {
            Bracket bracket = new Bracket();
            bracket.BracketId = bracketId;
            bracket.Name = name;
            return bracket;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BracketId
        {
            get
            {
                return _BracketId;
            }
            set
            {
                if (_BracketId != value)
                {
                    OnBracketIdChanging(value);
                    ReportPropertyChanging("BracketId");
                    _BracketId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BracketId");
                    OnBracketIdChanged();
                }
            }
        }
        private global::System.Int32 _BracketId;
        partial void OnBracketIdChanging(global::System.Int32 value);
        partial void OnBracketIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Round_BracketId", "Round")]
        public EntityCollection<Round> Rounds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Round>("Stumptown40Model.FK_Round_BracketId", "Round");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Round>("Stumptown40Model.FK_Round_BracketId", "Round", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stumptown40Model", Name="Match")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Match : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Match object.
        /// </summary>
        /// <param name="matchId">Initial value of the MatchId property.</param>
        /// <param name="roundId">Initial value of the RoundId property.</param>
        /// <param name="raceNumber">Initial value of the RaceNumber property.</param>
        public static Match CreateMatch(global::System.Int32 matchId, global::System.Int32 roundId, global::System.Int32 raceNumber)
        {
            Match match = new Match();
            match.MatchId = matchId;
            match.RoundId = roundId;
            match.RaceNumber = raceNumber;
            return match;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MatchId
        {
            get
            {
                return _MatchId;
            }
            set
            {
                if (_MatchId != value)
                {
                    OnMatchIdChanging(value);
                    ReportPropertyChanging("MatchId");
                    _MatchId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MatchId");
                    OnMatchIdChanged();
                }
            }
        }
        private global::System.Int32 _MatchId;
        partial void OnMatchIdChanging(global::System.Int32 value);
        partial void OnMatchIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoundId
        {
            get
            {
                return _RoundId;
            }
            set
            {
                OnRoundIdChanging(value);
                ReportPropertyChanging("RoundId");
                _RoundId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoundId");
                OnRoundIdChanged();
            }
        }
        private global::System.Int32 _RoundId;
        partial void OnRoundIdChanging(global::System.Int32 value);
        partial void OnRoundIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RaceNumber
        {
            get
            {
                return _RaceNumber;
            }
            set
            {
                OnRaceNumberChanging(value);
                ReportPropertyChanging("RaceNumber");
                _RaceNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RaceNumber");
                OnRaceNumberChanged();
            }
        }
        private global::System.Int32 _RaceNumber;
        partial void OnRaceNumberChanging(global::System.Int32 value);
        partial void OnRaceNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Racer1Id
        {
            get
            {
                return _Racer1Id;
            }
            set
            {
                OnRacer1IdChanging(value);
                ReportPropertyChanging("Racer1Id");
                _Racer1Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Racer1Id");
                OnRacer1IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Racer1Id;
        partial void OnRacer1IdChanging(Nullable<global::System.Int32> value);
        partial void OnRacer1IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Racer2Id
        {
            get
            {
                return _Racer2Id;
            }
            set
            {
                OnRacer2IdChanging(value);
                ReportPropertyChanging("Racer2Id");
                _Racer2Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Racer2Id");
                OnRacer2IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Racer2Id;
        partial void OnRacer2IdChanging(Nullable<global::System.Int32> value);
        partial void OnRacer2IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WinningRacerId
        {
            get
            {
                return _WinningRacerId;
            }
            set
            {
                OnWinningRacerIdChanging(value);
                ReportPropertyChanging("WinningRacerId");
                _WinningRacerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WinningRacerId");
                OnWinningRacerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _WinningRacerId;
        partial void OnWinningRacerIdChanging(Nullable<global::System.Int32> value);
        partial void OnWinningRacerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NextWinningMatchId
        {
            get
            {
                return _NextWinningMatchId;
            }
            set
            {
                OnNextWinningMatchIdChanging(value);
                ReportPropertyChanging("NextWinningMatchId");
                _NextWinningMatchId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NextWinningMatchId");
                OnNextWinningMatchIdChanged();
            }
        }
        private Nullable<global::System.Int32> _NextWinningMatchId;
        partial void OnNextWinningMatchIdChanging(Nullable<global::System.Int32> value);
        partial void OnNextWinningMatchIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NextWinningMatchSlot
        {
            get
            {
                return _NextWinningMatchSlot;
            }
            set
            {
                OnNextWinningMatchSlotChanging(value);
                ReportPropertyChanging("NextWinningMatchSlot");
                _NextWinningMatchSlot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NextWinningMatchSlot");
                OnNextWinningMatchSlotChanged();
            }
        }
        private Nullable<global::System.Int32> _NextWinningMatchSlot;
        partial void OnNextWinningMatchSlotChanging(Nullable<global::System.Int32> value);
        partial void OnNextWinningMatchSlotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NextLosingMatchId
        {
            get
            {
                return _NextLosingMatchId;
            }
            set
            {
                OnNextLosingMatchIdChanging(value);
                ReportPropertyChanging("NextLosingMatchId");
                _NextLosingMatchId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NextLosingMatchId");
                OnNextLosingMatchIdChanged();
            }
        }
        private Nullable<global::System.Int32> _NextLosingMatchId;
        partial void OnNextLosingMatchIdChanging(Nullable<global::System.Int32> value);
        partial void OnNextLosingMatchIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NextLosingMatchSlot
        {
            get
            {
                return _NextLosingMatchSlot;
            }
            set
            {
                OnNextLosingMatchSlotChanging(value);
                ReportPropertyChanging("NextLosingMatchSlot");
                _NextLosingMatchSlot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NextLosingMatchSlot");
                OnNextLosingMatchSlotChanged();
            }
        }
        private Nullable<global::System.Int32> _NextLosingMatchSlot;
        partial void OnNextLosingMatchSlotChanging(Nullable<global::System.Int32> value);
        partial void OnNextLosingMatchSlotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Match_NextLosingMatchId", "Match1")]
        public EntityCollection<Match> Match1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Match>("Stumptown40Model.FK_Match_NextLosingMatchId", "Match1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Match>("Stumptown40Model.FK_Match_NextLosingMatchId", "Match1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Match_NextLosingMatchId", "Match")]
        public Match Match2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Match>("Stumptown40Model.FK_Match_NextLosingMatchId", "Match").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Match>("Stumptown40Model.FK_Match_NextLosingMatchId", "Match").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Match> Match2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Match>("Stumptown40Model.FK_Match_NextLosingMatchId", "Match");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Match>("Stumptown40Model.FK_Match_NextLosingMatchId", "Match", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Match_NextWinningMatchId", "Match1")]
        public EntityCollection<Match> Match11
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Match>("Stumptown40Model.FK_Match_NextWinningMatchId", "Match1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Match>("Stumptown40Model.FK_Match_NextWinningMatchId", "Match1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Match_NextWinningMatchId", "Match")]
        public Match Match3
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Match>("Stumptown40Model.FK_Match_NextWinningMatchId", "Match").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Match>("Stumptown40Model.FK_Match_NextWinningMatchId", "Match").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Match> Match3Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Match>("Stumptown40Model.FK_Match_NextWinningMatchId", "Match");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Match>("Stumptown40Model.FK_Match_NextWinningMatchId", "Match", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Match_Racer1Id", "Racer")]
        public Racer Racer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Racer>("Stumptown40Model.FK_Match_Racer1Id", "Racer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Racer>("Stumptown40Model.FK_Match_Racer1Id", "Racer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Racer> RacerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Racer>("Stumptown40Model.FK_Match_Racer1Id", "Racer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Racer>("Stumptown40Model.FK_Match_Racer1Id", "Racer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Match_Racer2Id", "Racer")]
        public Racer Racer1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Racer>("Stumptown40Model.FK_Match_Racer2Id", "Racer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Racer>("Stumptown40Model.FK_Match_Racer2Id", "Racer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Racer> Racer1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Racer>("Stumptown40Model.FK_Match_Racer2Id", "Racer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Racer>("Stumptown40Model.FK_Match_Racer2Id", "Racer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Match_RoundId", "Round")]
        public Round Round
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("Stumptown40Model.FK_Match_RoundId", "Round").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("Stumptown40Model.FK_Match_RoundId", "Round").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Round> RoundReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("Stumptown40Model.FK_Match_RoundId", "Round");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Round>("Stumptown40Model.FK_Match_RoundId", "Round", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Match_WinningRacerId", "Racer")]
        public Racer Racer2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Racer>("Stumptown40Model.FK_Match_WinningRacerId", "Racer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Racer>("Stumptown40Model.FK_Match_WinningRacerId", "Racer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Racer> Racer2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Racer>("Stumptown40Model.FK_Match_WinningRacerId", "Racer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Racer>("Stumptown40Model.FK_Match_WinningRacerId", "Racer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stumptown40Model", Name="Racer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Racer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Racer object.
        /// </summary>
        /// <param name="racerId">Initial value of the RacerId property.</param>
        /// <param name="startSlot">Initial value of the StartSlot property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="organization">Initial value of the Organization property.</param>
        public static Racer CreateRacer(global::System.Int32 racerId, global::System.Int32 startSlot, global::System.String name, global::System.String organization)
        {
            Racer racer = new Racer();
            racer.RacerId = racerId;
            racer.StartSlot = startSlot;
            racer.Name = name;
            racer.Organization = organization;
            return racer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RacerId
        {
            get
            {
                return _RacerId;
            }
            set
            {
                if (_RacerId != value)
                {
                    OnRacerIdChanging(value);
                    ReportPropertyChanging("RacerId");
                    _RacerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RacerId");
                    OnRacerIdChanged();
                }
            }
        }
        private global::System.Int32 _RacerId;
        partial void OnRacerIdChanging(global::System.Int32 value);
        partial void OnRacerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StartSlot
        {
            get
            {
                return _StartSlot;
            }
            set
            {
                OnStartSlotChanging(value);
                ReportPropertyChanging("StartSlot");
                _StartSlot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartSlot");
                OnStartSlotChanged();
            }
        }
        private global::System.Int32 _StartSlot;
        partial void OnStartSlotChanging(global::System.Int32 value);
        partial void OnStartSlotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Organization
        {
            get
            {
                return _Organization;
            }
            set
            {
                OnOrganizationChanging(value);
                ReportPropertyChanging("Organization");
                _Organization = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Organization");
                OnOrganizationChanged();
            }
        }
        private global::System.String _Organization;
        partial void OnOrganizationChanging(global::System.String value);
        partial void OnOrganizationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FaceUrl
        {
            get
            {
                return _FaceUrl;
            }
            set
            {
                OnFaceUrlChanging(value);
                ReportPropertyChanging("FaceUrl");
                _FaceUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FaceUrl");
                OnFaceUrlChanged();
            }
        }
        private global::System.String _FaceUrl;
        partial void OnFaceUrlChanging(global::System.String value);
        partial void OnFaceUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CarUrl
        {
            get
            {
                return _CarUrl;
            }
            set
            {
                OnCarUrlChanging(value);
                ReportPropertyChanging("CarUrl");
                _CarUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CarUrl");
                OnCarUrlChanged();
            }
        }
        private global::System.String _CarUrl;
        partial void OnCarUrlChanging(global::System.String value);
        partial void OnCarUrlChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Match_Racer1Id", "Match")]
        public EntityCollection<Match> Matches
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Match>("Stumptown40Model.FK_Match_Racer1Id", "Match");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Match>("Stumptown40Model.FK_Match_Racer1Id", "Match", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Match_Racer2Id", "Match")]
        public EntityCollection<Match> Matches1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Match>("Stumptown40Model.FK_Match_Racer2Id", "Match");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Match>("Stumptown40Model.FK_Match_Racer2Id", "Match", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Match_WinningRacerId", "Match")]
        public EntityCollection<Match> Matches2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Match>("Stumptown40Model.FK_Match_WinningRacerId", "Match");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Match>("Stumptown40Model.FK_Match_WinningRacerId", "Match", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stumptown40Model", Name="Round")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Round : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Round object.
        /// </summary>
        /// <param name="roundId">Initial value of the RoundId property.</param>
        /// <param name="bracketId">Initial value of the BracketId property.</param>
        /// <param name="roundNumber">Initial value of the RoundNumber property.</param>
        public static Round CreateRound(global::System.Int32 roundId, global::System.Int32 bracketId, global::System.Int32 roundNumber)
        {
            Round round = new Round();
            round.RoundId = roundId;
            round.BracketId = bracketId;
            round.RoundNumber = roundNumber;
            return round;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoundId
        {
            get
            {
                return _RoundId;
            }
            set
            {
                if (_RoundId != value)
                {
                    OnRoundIdChanging(value);
                    ReportPropertyChanging("RoundId");
                    _RoundId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoundId");
                    OnRoundIdChanged();
                }
            }
        }
        private global::System.Int32 _RoundId;
        partial void OnRoundIdChanging(global::System.Int32 value);
        partial void OnRoundIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BracketId
        {
            get
            {
                return _BracketId;
            }
            set
            {
                OnBracketIdChanging(value);
                ReportPropertyChanging("BracketId");
                _BracketId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BracketId");
                OnBracketIdChanged();
            }
        }
        private global::System.Int32 _BracketId;
        partial void OnBracketIdChanging(global::System.Int32 value);
        partial void OnBracketIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoundNumber
        {
            get
            {
                return _RoundNumber;
            }
            set
            {
                OnRoundNumberChanging(value);
                ReportPropertyChanging("RoundNumber");
                _RoundNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoundNumber");
                OnRoundNumberChanged();
            }
        }
        private global::System.Int32 _RoundNumber;
        partial void OnRoundNumberChanging(global::System.Int32 value);
        partial void OnRoundNumberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Round_BracketId", "Bracket")]
        public Bracket Bracket
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bracket>("Stumptown40Model.FK_Round_BracketId", "Bracket").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bracket>("Stumptown40Model.FK_Round_BracketId", "Bracket").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bracket> BracketReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bracket>("Stumptown40Model.FK_Round_BracketId", "Bracket");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bracket>("Stumptown40Model.FK_Round_BracketId", "Bracket", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stumptown40Model", "FK_Match_RoundId", "Match")]
        public EntityCollection<Match> Matches
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Match>("Stumptown40Model.FK_Match_RoundId", "Match");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Match>("Stumptown40Model.FK_Match_RoundId", "Match", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
